ShopBaseballBats/ShopBaseballBats/Models/BaseballBats.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
//using System.Linq;
//using System.Web;


namespace ShopBaseballBats.Models
{
    public class BaseballBats
    {

        [Key]
        public int Id { get; set; }
       public int ModelYear { get; set; }
        [Display(Name = "Bat Brands")]
        public List<BatBrand>? BatBrands { get; set; }


      

        


    }
}

ShopBaseballBats/ShopBaseballBats/Controllers/BaseballBatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopBaseballBats.Data3;
using ShopBaseballBats.Models;

namespace ShopBaseballBats.Controllers
{
    public class BaseballBatsController : Controller
    {
        private readonly BaseballBatContext _context;

        public BaseballBatsController(BaseballBatContext context)
        {
            _context = context;
        }

        // GET: BaseballBats
        public async Task<IActionResult> Index()
        {
              //List<BatBrand> batBrands = await _context.BatBrands.ToListAsync();
              //List<BaseballBats> baseballBats = await _context.BaseballBats.ToListAsync();
              return _context.BaseballBats != null ? 
                          View(await _context.BaseballBats.ToListAsync()) :
                          Problem("Entity set 'BaseballBatContext.BaseballBats'  is null.");
        }

        // GET: BaseballBats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.BaseballBats == null)
            {
                return NotFound();
            }

            var baseballBats = await _context.BaseballBats
                .FirstOrDefaultAsync(m => m.Id == id);
            if (baseballBats == null)
            {
                return NotFound();
            }

            return View(baseballBats);
        }

        // GET: BaseballBats/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BaseballBats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( BaseballBats baseballBats)
        {
            if (ModelState.IsValid)
            {
                _context.Add(baseballBats);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(baseballBats);
        }

        // GET: BaseballBats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BaseballBats == null)
            {
                return NotFound();
            }

            var baseballBats = await _context.BaseballBats.FindAsync(id);
            if (baseballBats == null)
            {
                return NotFound();
            }
            return View(baseballBats);
        }

        // POST: BaseballBats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  BaseballBats baseballBats)
        {
            if (id != baseballBats.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(baseballBats);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BaseballBatsExists(baseballBats.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(baseballBats);
        }

        // GET: BaseballBats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.BaseballBats == null)
            {
                return NotFound();
            }

            var baseballBats = await _context.BaseballBats
                .FirstOrDefaultAsync(m => m.Id == id);
            if (baseballBats == null)
            {
                return NotFound();
            }

            return View(baseballBats);
        }

        // POST: BaseballBats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.BaseballBats == null)
            {
                return Problem("Entity set 'BaseballBatContext.BaseballBats'  is null.");
            }
            var baseballBats = await _context.BaseballBats.FindAsync(id);
            if (baseballBats != null)
            {
                _context.BaseballBats.Remove(baseballBats);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BaseballBatsExists(int id)
        {
          return (_context.BaseballBats?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public IActionResult Privacy()
        {
            return View();
        }
    }
}

ShopBaseballBats/ShopBaseballBats/Controllers/BatBrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopBaseballBats.Data3;
using ShopBaseballBats.Models;

namespace ShopBaseballBats.Controllers
{
    public class BatBrandController : Controller
    {
        private readonly BaseballBatContext _context;

        public BatBrandController(BaseballBatContext context)
        {
            _context = context;
        }

        // GET: BatBrand
        public async Task<IActionResult> Index()
        {
            
              return _context.BatBrands != null ? 
                          View(await _context.BatBrands.ToListAsync()) :
                          Problem("Entity set 'BaseballBatContext.BatBrands'  is null.");
        }

        // GET: BatBrand/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.BatBrands == null)
            {
                return NotFound();
            }

            var batBrand = await _context.BatBrands
                .FirstOrDefaultAsync(m => m.Id == id);
            if (batBrand == null)
            {
                return NotFound();
            }

            return View(batBrand);
        }

        // GET: BatBrand/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BatBrand/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Length,Weight,Price,BrandName,ModelNames,DescriptionHtml,Cart")] BatBrand batBrand)
        {
            if (ModelState.IsValid)
            {
                _context.Add(batBrand);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(batBrand);
        }

        // GET: BatBrand/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BatBrands == null)
            {
                return NotFound();
            }

            var batBrand = await _context.BatBrands.FindAsync(id);
            if (batBrand == null)
            {
                return NotFound();
            }
            return View(batBrand);
        }

        // POST: BatBrand/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Length,Weight,Price,BrandName,ModelNames,DescriptionHtml,Cart")] BatBrand batBrand)
        {
            if (id != batBrand.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(batBrand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BatBrandExists(batBrand.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(batBrand);
        }

        // GET: BatBrand/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.BatBrands == null)
            {
                return NotFound();
            }

            var batBrand = await _context.BatBrands
                .FirstOrDefaultAsync(m => m.Id == id);
            if (batBrand == null)
            {
                return NotFound();
            }

            return View(batBrand);
        }

        // POST: BatBrand/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.BatBrands == null)
            {
                return Problem("Entity set 'BaseballBatContext.BatBrands'  is null.");
            }
            var batBrand = await _context.BatBrands.FindAsync(id);
            if (batBrand != null)
            {
                _context.BatBrands.Remove(batBrand);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BatBrandExists(int id)
        {
          return (_context.BatBrands?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ShopBaseballBats/ShopBaseballBats/Views/BaseballBats/Create.cshtml
@model ShopBaseballBats.Models.BaseballBats

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BaseballBats</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ModelYear" class="control-label"></label>
                <input asp-for="ModelYear" class="form-control" />
                <span asp-validation-for="ModelYear" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="BatBrands" class="control-label"></label>
                <input asp-for="BatBrands" class="form-control" />
                <span asp-validation-for="BatBrands" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BatBrands" class="control-label">Try to add Model Name here.</label>
                <input asp-for="BatBrands" class="form-control" />
                <span asp-validation-for="BatBrands" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Home Page</a>
</div>

ShopBaseballBats/ShopBaseballBats/Views/BaseballBats/Delete.cshtml
@model ShopBaseballBats.Models.BaseballBats

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BaseballBats</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModelYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModelYear)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ShopBaseballBats/ShopBaseballBats/Views/BaseballBats/Details.cshtml
@model ShopBaseballBats.Models.BaseballBats

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>BaseballBats</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BatBrands)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BatBrands)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ShopBaseballBats/ShopBaseballBats/Views/BaseballBats/Edit.cshtml
@model ShopBaseballBats.Models.BaseballBats

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BaseballBats</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ModelYear" class="control-label"></label>
                <input asp-for="ModelYear" class="form-control" />
                <span asp-validation-for="ModelYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ShopBaseballBats/ShopBaseballBats/Views/BaseballBats/Index.cshtml
@model IEnumerable<ShopBaseballBats.Models.BaseballBats>

@{
    
    ViewData["Title"] = "Home";
    var brands = new string[]
    {
    "Louisville Slugger",
    "Easton",
    "Rawlings"
    };
    
}

<h1>Your source for top rated fastpitch bats.</h1>

<p>
    <a>We provide the top rated bats from the top rated brands.</a>
</p>

    <div class="row">
        
        <div class="col-md-4">
            <h2><a asp-area="" asp-controller="BatBrand" asp-action="Index">Louisville Slugger</a></h2>
            <img src="@Url.Content("~/Images/lxt22.jpg")"
                alt="Louisville Slugger LXT Bat"
                class="img-responsive" />
                 
        </div>
        <div class="col-md-4">
            <h2><a asp-area="" asp-controller="BatBrand" asp-action="Index">Easton</a></h2>
            <img src="@Url.Content("~/Images/eastonGhost20.jpg")"
                alt="Easton Ghost Fastpitch Bat"
                class="img-responsive" />
               
        </div>
        <div class="col-md-4">
            <h2><a asp-area="" asp-controller="BatBrand" asp-action="Index">Rawlings</a></h2>
            <img src="@Url.Content("~/Images/rawlingsMantra.jpg")"
                alt="Rawlings Mantra Fastpitch Bat"
                class="img-responsive" />
                 
        </div>
       
     </div>

    